// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4AAUuZ8as_sk63vCSPQZDNxSxRrXUpmY',
    appId: '1:1054852316994:web:b9c41d90a5743f978252db',
    messagingSenderId: '1054852316994',
    projectId: 'authentications-5a351',
    authDomain: 'authentications-5a351.firebaseapp.com',
    storageBucket: 'authentications-5a351.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7osHpVfX08jMlXeEksJOmby1XX7JlMQ',
    appId: '1:1054852316994:android:0e5ef3a914052bf98252db',
    messagingSenderId: '1054852316994',
    projectId: 'authentications-5a351',
    storageBucket: 'authentications-5a351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7JSSOQ8AnaHr-2jfesY-w2nDvAScYEP8',
    appId: '1:1054852316994:ios:808870f5ca75f9ab8252db',
    messagingSenderId: '1054852316994',
    projectId: 'authentications-5a351',
    storageBucket: 'authentications-5a351.appspot.com',
    iosBundleId: 'com.example.authentications',
  );
}
